### PR TITLE
Lesson 2.1

### PR DESCRIPTION
**Pull request by bhoconnor**
Added index.html file (& for testing purposes, did a couple text additions that i then removed)

### CODE REVIEW

**Review by esthicodes — COMMENTED** [review]
Is this a test file

**Comment by bhoconnor** [comment]
Hi @Estheryu991 , yes it is a test file, thanks--are you with Code the Dream?

**Comment by esthicodes** [comment]
> Hi @Estheryu991 , yes it is a test file, thanks--are you with Code the Dream?

Yes, I am =) Nice work btw

**Comment by bhoconnor** [comment]
Nice, thanks!!

**Pull request merged**
